### ISSUE TITLE
support idea

### ISSUE THREAD

**Issue by CashOver** [haven1433/HexManiacAdvance#103]
I would like to know could it support pokémon black/white 2 ?

**Comment by haven1433** [comment]
HexManiacAdvance is a hex editor designed for editing Pokemon GBA games. It specifically targets the English games Ruby (AXVE), Sapphire (AXPE), FireRed (BPRE), LeafGreen (BPGE), and Emerald (BPEE). It may eventually support other GBA games, but there is no plan to support other pokemon games.
