### ISSUE TITLE
Scripts getting deleted when editing game corner scripts.

### ISSUE THREAD

**Issue by Thoma-main** [haven1433/HexManiacAdvance#149]
I haven't noticed this problem show up anywhere else within the program, only within the game corner scripts.

When attempting to change the pokemon that is given for each prize within the game corner, HMA seems to just set a huge chunk of memory to "FF" deleting sections of the game corner script. 

I know it can sometimes automatically repoint scripts if the size changes, but I don't think that's the case here for several reasons.
1. There isn't actually a change in size of the script, all im doing is decrementing a number by 1.
2. I check the diff since last save tool after it FFs the huge chunk of memory and it isn't repointing it anywhere else, its only FFing the memory. 

### **Steps to Reproduce:**
1. Open HMA 0.5.1
2. Navigate to the game corner pokemon prize script (Use the map or go directly there with the address: <16CC00>)
4. Change the 63 in "setvar 0x4001 63" to a 62
5. Watch as a huge chunk of memory is deleted: 

![image](https://user-images.githubusercontent.com/56980219/233792589-f2410000-7a7d-42fb-a35f-cf945ef2239b.png)

Diff since last save to show that it isn't simply being moved somewhere else:
![image](https://user-images.githubusercontent.com/56980219/233792612-721621e2-05b7-4cc9-8414-37fa6a985cdc.png)

### **Important Notes:**
This only happens when you are editing a a script that you are not directly navigated to (its a script thats connected to the currently viewed script, usually via "goto")

![image](https://user-images.githubusercontent.com/56980219/233792515-5a54c9cf-1ca0-4e04-a864-20255fdcf766.png)
If you edit it in the image above, it causes the huge memory chunk to get deleted.

![image](https://user-images.githubusercontent.com/56980219/233792498-be365782-1c40-4852-a41d-d9d738929190.png)
If you edit it in the image above, it does not cause the huge memory chunk to get deleted.

Please let me know if you need any more info or if I should show any other screenshots.

**Comment by haven1433** [comment]
I think I managed to figure this out. Should be fixed in 0.5.2.
