### ISSUE TITLE
[Feature Request] Search Filters/Parameters

### ISSUE THREAD

**Issue by LOuroboros** [haven1433/HexManiacAdvance#177]
I just thought about a neat suggestion to make; the ability to use filters or special parameters when using the program's search function.

For example, a filter to match the whole word.

If I wanted to look up the string for "girl" in the game's intro and didn't want to deal with lots of unwanted miscellaneous results, I would like to use a filter that lets me match the text string "girl" and omit any results that contained the word as a part of a larger sentence.

Normally, things like `git grep` use `-w`, for reference. I'd type `git grep -w "GIRL"` in the terminal, and it would find me any usages of the word "GIRL" as is, omitting any actual sentences that use the word in the process.

**Comment by ShinyTillDawn** [comment]
Hi Lunos; it's so great to see you!

Finding exact words would be a great feature (sort of like typing "search terms" on Google), but I'm not sure how much code we'd have to rewrite to get it working well.

**Comment by haven1433** [comment]
Currently Find has 2 toggles:
* "Look only in this one tab" / "Look in all open tabs"
* "Match exact case" / "find upper and lower case"

Would it make sense to add a third option, something like "match only entire string" so that it only finds things that have pointers and the FF ending byte?

**Comment by ShinyTillDawn** [comment]
> Would it make sense to add a third option...?
Time to update my tutorial lol

**Comment by haven1433** [comment]
added to the backlog
