### ISSUE TITLE
Primary tileset only displays 128x128 of the full image

### ISSUE THREAD

**Issue by Zexlo** [haven1433/HexManiacAdvance#195]
No matter what, the primary tileset in HMA will only accept an 128x128 image, because of this some of my custom tiles are inaccessible
in the image editor despite other tools such as advance map exporting/importing and using the full image size just fine.

**Comment by haven1433** [comment]
Which map are you trying to edit? I wonder if it's a map with a smaller primary tileset.

**Comment by Zexlo** [comment]
it was the outdoor tileset, no matter which outdoor map I edit the full
image is always cut off

**Comment by haven1433** [comment]
I just checked vanilla FireRed and vanilla Emerald, in both cases the tileset appears much larger than 128x128 when I open it in the image editor. Can you advise? I feel like I'm not seeing the bug.

![image](https://github.com/haven1433/HexManiacAdvance/assets/10834600/aec8ede8-21a2-4f58-bd4c-8fc3a624cd1f)

![image](https://github.com/haven1433/HexManiacAdvance/assets/10834600/836f4042-fc6f-43a8-b9b9-48f7b890af64)

**Comment by Zexlo** [comment]
My edited rom only allows me to view and edit the first 128x128 of the full tileset, but i can access tiles past that limit in the block editor fine.
![image](https://github.com/haven1433/HexManiacAdvance/assets/96223408/493feb25-142d-4a76-b9cf-0ec1214e7df6)
![image](https://github.com/haven1433/HexManiacAdvance/assets/96223408/49207a02-00bf-42de-a9c5-9f77185698c7)

**Comment by haven1433** [comment]
I notice that your tileset doesn't have a slider across the top. That makes me think that HMA might think that it's an image, not a tileset. Try looking at the format in the hex editor.

![goto-tileset](https://github.com/haven1433/HexManiacAdvance/assets/10834600/7a7c8030-be19-4d70-b819-a297319987e6)

Edit Map Header -> View Table in Data Tab -> layout -> blockdata1 -> tileset

From there, you should see that the format is something like `lzt4`. If you instead see `lzs4x16x16`, that's probably the problem.

**Comment by Zexlo** [comment]
yeah that's the issue, thanks! any idea how to re-format it as a tileset?

**Comment by haven1433** [comment]
> smaller than usual
tilesets don't have fixed size, I wonder if your tileset is just smaller than the default. Note that in the data tab, right after `lz`, there's a number that should take up the next 3 cells. That number/32 is how many tiles you have stored in the tileset. Looks like your tileset is 16x20, so I'd expect the number to be close to 10240. If so, then you may just want to expand the tileset.

You can expand the primary/secondary tilesets from the map's header panel using these buttons
![image](https://github.com/haven1433/HexManiacAdvance/assets/10834600/f341dbfe-89cc-4b4b-8a42-f21633546ea2)

**Comment by Zexlo** [comment]
thanks for the help and good luck with future releases of the tool, its awesome.
