### ISSUE TITLE
Graphics Issues

### ISSUE THREAD

**Issue by Portlyinformant** [haven1433/HexManiacAdvance#205]
Hello, I have been happily using this software for a while but have had an issue for quite a long time with certain graphics I import or edit being garbled. This specifically happens during the copyright part of the graphics. Basically the graphics get garbled when the game is run. Sometimes when I undo and redo an edit I make on the graphics it suddenly becomes garbled again. Making basic edits on the picture sometimes changes what exactly get's garbled on the picture.

**Comment by jmynes** [comment]
This sounds kind of like the palette issue, is it blinking on/off on the title screen?
A screenshot or video would be helpful

**Comment by haven1433** [comment]
Closed for lack of information from OP

**Comment by Portlyinformant** [comment]
![Image](https://github.com/user-attachments/assets/770177c7-546e-4bd7-910e-356300e3309b)
![Image](https://github.com/user-attachments/assets/94be82ad-9403-4fc0-ae6f-b6dab8eadc6f)
![Image](https://github.com/user-attachments/assets/c5bde2fc-a345-4e13-a741-115a99053706)
![Image](https://github.com/user-attachments/assets/5c943503-3361-46d3-bf27-7a60c9661989)

I know it's been ages since I last sent this but here's examples of what would happen when I edit the copyright. There's no issues with blinking on and off on the title screen.
