### ISSUE TITLE
Stuck on script description when drag&dropping script into window

### ISSUE THREAD

**Issue by purrfectdoodle** [haven1433/HexManiacAdvance#208]
Hi there! I'm very new to HMA and romhacking in general, so this might be my own fault somehow.

I downloaded the last version of HMA and I'm using a clean vanilla Emerald ROM. When I drag&drop one of the default scripts (like the fairy type script, or the physical/special split) into the HMA window, the description popin that is displayed while holding remains upon release, and nothing happens:

![image](https://github.com/haven1433/HexManiacAdvance/assets/105788407/4048ce53-7321-46f5-94ed-cd3e3d52eb6d)

What could the issue be?

**Comment by ShinyTillDawn** [comment]
Interesting. Does this error still occur on Hex Maniac Advance 0.5.6? It could be that the program is lagging.

**Comment by haven1433** [comment]
Closed for lack of information from OP
