### ISSUE TITLE
Legendary encounters freeze

### ISSUE THREAD

**Issue by Wazupower** [haven1433/HexManiacAdvance#209]
![image](https://github.com/haven1433/HexManiacAdvance/assets/29546560/4ffa8237-bca6-4f97-8832-ec9273cd7487)

While playing and trigger a legendary encounters the game freeze

I don't know if it's useful but my game is a french version

**Comment by ShinyTillDawn** [comment]
Hex Maniac Advance does not support non-English ROMs.
