### ISSUE TITLE
MacOS support.

### ISSUE THREAD

**Issue by jrapf32** [haven1433/HexManiacAdvance#211]
I have tried wine it doesn’t work. On mac you can build .net apps. This project uses Windows libraries that MacOS's .net doesn't support. Please switch over to non Windows dependencies.

**Comment by haven1433** [comment]
The UI layer is written in WPF as a separate assembly. The project is open source, and I encourage people to write custom UI layers if they like. I do not personally intend to build a non-WPF UI for this project.
