### ISSUE TITLE
Where is the Fairy Type script?!

### ISSUE THREAD

**Issue by Tyrranux** [haven1433/HexManiacAdvance#215]
I looked up the Utilities page and there's nothing there! No code to copy, no link to download, NOTHING! And that's just tip of the iceberg that is the nightmare I've been having with your program!

**Comment by haven1433** [comment]
This utilities menu here? 
![image](https://github.com/haven1433/HexManiacAdvance/assets/10834600/663e40f0-bef6-4ed0-8cea-6ee37f19d7fb)

And then the script is in the `Add Mechanics From Later Generations` folder.

**Comment by Tyrranux** [comment]
Uhhh, no, that's the "Go To the Hexadecimal Tables" option. Every other
instance of clicking on the word "Script" in all my hours fiddling with
this thing has taken me right to those tables, why would I expect any
differently here? Now if it were labeled something more precise like "Add
Additional Features".......

**Comment by haven1433** [comment]
I have no idea what you're talking about. You said you were looking for a Fairy type script, you said you checked in utilities... So I looked in the utilities menu, and saw something that says "scripts" which is what you were looking for...

> Add Additional Features

That sounds pretty close to "Add Mechanics From Later Generations". So it sounds like you're all set, unless you're asking something else and I'm not understanding you.
