### ISSUE TITLE
Add New Pokemon doesn't work right

### ISSUE THREAD

**Issue by Tyrranux** [haven1433/HexManiacAdvance#216]
Got tired of replacing Pokemon and just wanted to add a new one. It does show up in my Rom on playthroughs, the code is fine, game doesn't crash, but it just comes up as "????????" and doesn't use the sprite I imported. How do I fix this?

**Comment by haven1433** [comment]
Did you notice this warning about limiters when expanding the table?
![image](https://github.com/haven1433/HexManiacAdvance/assets/10834600/e4afcfbd-610d-4a47-9b3f-0901ca277da1)

If you want to expand those tables, you need to update the limiters. There's scripts in the utilities to help with expanding some, like moves and items, but HMA doesn't include a safe way to expand the pokemon.

For more assistance, I recommend checking out the program's [Discord Server](https://discord.com/invite/x9eQuBg), where you can find thousands of users that can help with specific questions.

**Comment by Tyrranux** [comment]
Why do I even bother asking questions to people that find creative ways to
give no helpful answers?

**Comment by haven1433** [comment]
Why do I bother giving detailed answers to people who just want short answers?

Fine, here's the short answer:

> How do I fix this?

You need to revert your change. You can't safely expand the pokemon table using HMA.
