### ISSUE TITLE
New Object Templates Missing

### ISSUE THREAD

**Issue by TheFruityOne** [haven1433/HexManiacAdvance#229]
I'm using an expanded version of FireRed so I suspect the problem lies there, but when I click to add a new object all the template sprites are missing, it just shows the question mark placeholder. 

This might be a silly question but do you know of a way to resolve that without starting again? Thanks!

**Comment by haven1433** [comment]
There's a pointer at `05F2F4` in BPRE0 (English FireRed 1.0) that leads to the overworld data.

(1) Goto 05F2F4
(2) Follow the pointer there
(3) At the new address, type `^graphics.overworld.sprites[data<[starterbytes:|h paletteid:|h secondid:|h length: width: height: info.|t|palSlot::|shadowSize:|inanimate.|reflectionPalette. footprint.owfootprints unused: distribution<> sizedraw<> animation<> sprites<`osl`> ramstore<>]1>]20`

That `20` at the end says that you expect that the table contains `20` elements. If everything's alright in your game, that should show you a few overworld characters. If that works the way you expect, you can change the `20` to however many overworld characters are in your expanded version. By default there's 151, but I don't know how many your game has.
