### ISSUE TITLE
Wild pokemon not appearring

### ISSUE THREAD

**Issue by Wazupower** [haven1433/HexManiacAdvance#231]
![image](https://github.com/user-attachments/assets/11fe884e-7bcc-4a24-91d4-f4bc9a418672)
Hello !
I am strugling adding a new wild data set to a new area that I create myself, as we can see on the image I added wild pokemon to grass in my new area but when I test there is no wild pokemon in the area.
Do I have forgotten something ?
I post it on the discussions tab but not sure it was the right place, so I post that here too.
Thanks in advance !

**Comment by Wazupower** [comment]
I think I figured out about a solutions, but I don't know if it's the correct way.
First I add a new wild data using Advance map in my new area.
Then back in HMA all my data.pokemon.wild was empty, anywhere on the map, HMA doesn't know where all the wild data was moved.
So I search for a data table that I know was in the old data.pokemon.wild
![image](https://github.com/user-attachments/assets/0fc6e982-c06b-4f13-a797-5c129ca2aab7)
When I identifie were was move my new wild data I coppy the address and change it in the .toml file.
![image](https://github.com/user-attachments/assets/1ce0b1c3-cd0f-456a-923f-ce26fc87c25c)
Now in HMA all my wild data is back in place and HMA know where my wild data is.

I hope this is understandable and help someone.

**Comment by haven1433** [comment]
When you first open your game in HMA, it generates a .toml file that makes educated guesses on where all your data is. The closer your game is to a vanilla game, the better these guesses will be. If you edit data with another program after that, HMA won't know about the edits or where things are unless you manually edit that .toml file. So it sounds like you did things right.

Of course, you don't have to use AdvanceMap at all, you can create and edit wild data directly within HMA. But if you _do_ use AdvanceMap to edit something, it makes sense that you'd need to edit the .toml file after to get HMA back in sync.
