### ISSUE TITLE
Assertion Failed: `Debug.Assert(IsSelected(selectionPoint));`

### ISSUE THREAD

**Issue by rtzoeller** [haven1433/HexManiacAdvance#51]
I triggered an assertion by right clicking on an invalid cell.

Reproducing steps:
1. File >> New
1. Right click an empty cell
1. Observe the following error:
![image](https://user-images.githubusercontent.com/573497/70964343-1978ac00-2051-11ea-81d0-4884f4bc7bd7.png)

**Comment by haven1433** [comment]
See #54 for the fix
