### ISSUE TITLE
Assertion Failed: Debug.Assert(run.Length > 0); // writing an anchor of length zero is stupid.

### ISSUE THREAD

**Issue by rtzoeller** [haven1433/HexManiacAdvance#52]
I attempted to open a Ruby ROM I had laying around and immediately had an assertion fail. Let me know if you need the file for a reproducing case.

The `anchorName` during the failure was `"eggmoves"`.

![image](https://user-images.githubusercontent.com/573497/70967007-952b2680-205a-11ea-9146-157847f92fad.png)

**Comment by haven1433** [comment]
Ruby is part of my standard test set, and I'm not seeing this. I wonder if you have a different version of ruby (1.1) or maybe it has some edits. Either way, yes, I'll need some more data to reproduce this case.
