### ISSUE TITLE
Dialogues text ?

### ISSUE THREAD

**Issue by raousoft** [haven1433/HexManiacAdvance#70]
Hi
I wonder if it's possible to add dialogues text ?

**Comment by haven1433** [comment]
Can you be a bit more specific? What text / resource are you talking about?

**Comment by raousoft** [comment]
@haven1433 
Dialogues text, like this one :
![image](https://user-images.githubusercontent.com/37517008/87926094-1b886a80-ca79-11ea-9b41-9850d46b232b.png)

I know there are a lot a other tools for that, but all of them kinda don't assemble them in a more organized one place for all the text.

**Comment by haven1433** [comment]
As you mentioned, there isn't a single table that contains all the dialog text. So even in HexManiacAdvance, there can't be a single-source-of-truth that holds them all.

However, Ctrl+F *does* work on text. Some of the text can be detected automatically based on its placement and its pointers. The text that can't be detected automatically can still be found through Ctrl+F.

Using the example from your screenshot:

* Open Ruby 1.0
* Edit -> Find (or Ctrl+F)
* type `we're going to get all the sand` into the search and press `enter`.
* HexManiacAdvance finds a single result and jumps to it.
![image](https://user-images.githubusercontent.com/10834600/87932723-98075300-ca51-11ea-8049-5d39add1aaba.png)

If the highlighted bytes are not formatted, you can right-click and choose `Display as Text`, which will usually be able to discover the right formatting.

**Comment by raousoft** [comment]
The idea is to assemble all dialogues text in one place since nobody did that till now.

**Comment by haven1433** [comment]
While it's technically possible to do this, it would be a ton of work since it's different for each game, and the end result would be so large that you'd still need to use Ctrl+F to search through it for whatever text you're wanting to change. So since Ctrl+F already works, I don't see what benefit would be gained from creating anchors for every piece of text in the game.
