### ISSUE TITLE
Pokedex Editor Not Working

### ISSUE THREAD

**Issue by Clover427** [haven1433/HexManiacAdvance#71]
Hello, I recently downloaded HMA in order to reorder the pokedex for the project I'm making. Unfortunately, whenever I try and open up the pokedex editor, I get notified that an error has occurred and that something might be wrong with the program, and then it tells me to close it. I'm not sure what I should do to fix this issue.

[https://pastebin.com/BsYSGa7i](url) <- Crash Report

**Comment by haven1433** [comment]
Clover427,

Thanks for reporting this issue! I suspect that it's one that I've fixed in master, and just hasn't made it into a release yet. I hope to release version 0.3.6 later this month. I'll let you know when that drops, and hopefully that'll fix the issue you're seeing.

I'll leave this issue open until the next version is out and you have a chance to try it out.

**Comment by Clover427** [comment]
Ok, Thank you!

**Comment by haven1433** [comment]
Version 0.3.6 is now released, and hopefully fixes the issues you were having. If not, please let me know.

**Comment by Clover427** [comment]
I downloaded the new version, and I was able to open up the regional dex editor. The only thing is that whenever I try to edit the Pokedex, each pokemon comes up as a question mark instead of their sprite, except for Bulbasaur. I was given the option to update the dex conversion tables once and it had removed the question marks, but I exited out and when I went back it won't let me update the tables. 
![Question 2](https://user-images.githubusercontent.com/69167296/89741870-e6ad7900-da62-11ea-8398-89f6c80eca33.PNG)
![Not Working](https://user-images.githubusercontent.com/69167296/89741911-42780200-da63-11ea-9e98-5293f0c800cd.PNG)

What should I do?

**Comment by haven1433** [comment]
Do you have a Discord account? If so, consider joining the [HexManiacAdvance development server](https://discordapp.com/channels/556701929904799756/629541218665365505/741005821219045418). At this point, whatever is going wrong may be specific to your rom and the changes that you've made. We may be able to have more of a dialog about the issue through Discord than we can though GitHub.

**Comment by Clover427** [comment]
Yes, I do have a discord. I'll be sure to join that. The link that you put doesn't seem to take me to an invite link, but instead just to my discord home page. Are you able to send an invite link?

**Comment by haven1433** [comment]
Try [this one](https://discord.gg/x9eQuBg), hopefully it works better. Sorry about the mixup. I also updated the original link, in case someone reading through this in the future clicks it.

**Comment by haven1433** [comment]
Just to follow up: we discussed on discord and figured out that your problem was fixed by switching to version 0.3.6. But then you'd encountered an upgrade bug from importing your 0.3.5 toml with the 0.3.6 app. That should be fixed in the next version.
