### ISSUE TITLE
HM MENU ISSUE

### ISSUE THREAD

**Issue by Shermquest** [haven1433/HexManiacAdvance#72]
When I expand the move pool it seems to cause a menu issue with the HM moves where there is no text saying "CUT" or "ROCK SMASH" even though I can see the menu text telling me what these commands do.

**Comment by haven1433** [comment]
Thanks for reporting! This should be fixed in the current source. You can build latest to get the fix, or you can wait until 0.4 comes out sometime around the new year.

**Comment by Shermquest** [comment]
Thank you for a swift response and a solution in coming. 😀 Also your editor is amazing so please keep the good work going.

**Comment by haven1433** [comment]
0.4 is released! I believe the issue you mentioned should now be fixed. Note that expanding the move pool does require using the `Make Moves Expandable` option in the Utilities menu. Otherwise you'll probably notice issues with your PP values not updating correctly.
