### ISSUE TITLE
Error opening rom

### ISSUE THREAD

**Issue by Darthbr** [haven1433/HexManiacAdvance#73]
Hello, im having a issue, can open my hack rom on it, im uploading the crash log
[crash.log](https://github.com/haven1433/HexManiacAdvance/files/5618786/crash.log)

**Comment by haven1433** [comment]
Here's the error message from the log:
`A matriz de destino não é grande o suficiente para copiar todos os itens da coleção. Verifique o índice e o tamanho da matriz.`

I think I can fix the symptom, which *might* let your rom load, but there's something going on that's causing the error that I'll need to investigate. Feel free to hop over to the discord server if you'd like to help me solve this:

Discord Invite: wDxvh6HB37

**Comment by haven1433** [comment]
0.4 is released, which hopefully fixes this issue. I never got further info from you though, so I'm unsure whether this issue is actually fixed.
