### ISSUE TITLE
[Feature Request] Option to see colors in "0-255 Color Mode"(?)

### ISSUE THREAD

**Issue by LOuroboros** [haven1433/HexManiacAdvance#82]
Hi. I used HMA earlier to see the edits of my party screen colors in real time. Pretty cool feature.
However, I'm noticing that the way in which the program visualizes color codes goes from 0 to 31.

It would be super helpful if the user could enable a mode to show them in whatever color mode goes from 0 to 255. That way even people using the decompilation projects made by Pret could benefit from HMA's spriting capabilities and quickly paste over colors from HMA to the palette files used by said projects :eyes:

**Comment by haven1433** [comment]
Added in https://github.com/haven1433/HexManiacAdvance/commit/edc2ed9fde9e4f77db6bb4d75e41610b9f1d9ac5
