### ISSUE TITLE
[Request] Visual of "elevation" for front sprite like back sprite has.

### ISSUE THREAD

**Issue by Goretantath** [haven1433/HexManiacAdvance#93]
I've been trying to add a section in the UI like - "
[[NamedAnchors]]
Name = '''graphics.pokemon.sprites.coordinates.back'''
Address = 0x1A92514
Format = '''[size.|t|width::|height:: yOffset. render|render=graphics.battle.background.sprites/0/battlemap/|0|0|240|112|graphics.pokemon.sprites.back|40|48||yOffset unused:]data.pokemon.names''' "
but for the changes made with - " [[NamedAnchors]]
Name = '''graphics.pokemon.sprites.elevation'''
Address = 0x1AA8F12
Format = '''[elevation.]data.pokemon.names''' "

I can remove a section and it will be removed from the UI but whenever i try to add something like - "
[[NamedAnchors]]
Name = '''graphics.pokemon.sprites.coordinates.front'''
Address = 0x1AA8F12
Format = '''[size.|t|width::|height:: yOffset. render|render=graphics.battle.background.sprites/0/battlemap/|0|0|240|112|graphics.pokemon.sprites.front|40|48||yOffset unused:]data.pokemon.names''' "
nothing seems to change.

I would like to request either a new section be added by default or the section already there also include the front sprite in the opponent's section of the battlefield. It's really annoying to have to load up the game each time to line up the front sprite for over a thousand pokemon.

**Comment by haven1433** [comment]
I think what you're asking for is already implemented. Here's a screenshot from a vanilla FireRed:

![image](https://user-images.githubusercontent.com/10834600/184268083-ba130848-e7e4-41c1-bfae-2033b3a864f8.png)

As you can see, you can see a visualization for both the front sprite and the back sprite. Is this what you're asking for, or are you asking for something different?

**Comment by haven1433** [comment]
Without more info, there's nothing for me to do here.

**Comment by Goretantath** [comment]
Weird.. i loaded a vanilla firered and the front sprite section is missing... ill try re-downloading hex and see if i just broke something..

**Comment by Goretantath** [comment]
I think i found the reason, rev 1 is showing it but the original fire red rom wont..

**Comment by Goretantath** [comment]
Yep vanilla firered does indeed show this, somehow i named an edited fire red the same as my backup copy and thought it was vanilla, sorry for the confusion.
