### ISSUE TITLE
[Feature Request] Ability to highlight specific chunk of code

### ISSUE THREAD

**Issue by LOuroboros** [haven1433/HexManiacAdvance#94]
Title.

HxD, another hex editor, has a feature that allows you to highlight/select a specific chunk of code by specifying a Start offset and an End offset.

It sounds like a basic feature that could come in handy for HMA, specially coupled with its ability to read Thumb code. Highlighting specific chunks could help copy/read specific functions of code, I imagine.

![HxD64_20220808_101956006](https://user-images.githubusercontent.com/4485172/183427921-623b9aea-57ed-4c8e-b7e5-0328d9f1f29f.png)

![HxD64_20220808_101958212](https://user-images.githubusercontent.com/4485172/183427927-b4301006-049f-4175-bd4f-5b3feedb1d7e.png)

**Comment by haven1433** [comment]
This feature has never really made sense to me. There's already a goto feature that you can use to jump to a specific byte, and then an indicator to tell you how many bytes you've selected. What's the use case for bringing up a separate dialog and typing in an address and a length, rather than just clicking and dragging to select the bytes you want?

**Comment by LOuroboros** [comment]
> This feature has never really made sense to me. There's already a goto feature that you can use to jump to a specific byte, and then an indicator to tell you how many bytes you've selected. What's the use case for bringing up a separate dialog and typing in an address and a length, rather than just clicking and dragging to select the bytes you want?

It's faster to select the chunk automatically when you know the Start and End points, compared to having to drag over the mouse and select bytes?

**Comment by haven1433** [comment]
![image](https://user-images.githubusercontent.com/10834600/185032796-a14540b8-e0aa-4417-9e96-54c6ed709214.png)

Rather than adding a dialog. I've modified the bottom bar so that the address and number of selected bytes are now editable, rather than being read-only.

**Comment by LOuroboros** [comment]
But what if you don't know the length? What if I wanted to select everything from X to Y offset which is actually, exactly what I wanted to do when I opened this Feature Request ticket?

I mean, being able to select based on Length is fine too and it's a feature that HxD also has, but that's not what I suggested.
