### ISSUE TITLE
"Gender Ratio: 191" displays for all Pokemon with a gender ratio of 25% male, 75% female

### ISSUE THREAD

**Issue by jmynes** [haven1433/HexManiacAdvance#99]
When loading Fire Red and also Fire Red based ROMhacks into the latest release build of Hex Maniac Adventure, certain Gender Ratio entries read as "191", rather than Genderless, or a ratio.

Tested with: `1636 - Pokemon Fire Red (U)(Squirrels).gba`
See list: https://bulbapedia.bulbagarden.net/wiki/Category:Pok%C3%A9mon_with_a_gender_ratio_of_one_male_to_three_females

**Comment by jmynes** [comment]
For context, I'm new to Pokemon hex editing/inspection, and am only using this to get pokemon stats/abilities etc into a CSV. If 191 is integral to the game's code or something, this can probably be closed.

**Comment by haven1433** [comment]
Thanks for the report! This issue was also noticed over on the discord server, so it's already fixed in the master branch. You can [join the discord server](https://discord.gg/x9eQuBg), wait for 0.4.5, or build from source to get a version with the fix.
